### ISSUE TITLE
Versión tomcat

### ISSUE THREAD

**Issue by AleDH** [ctt-gob-es/SIGM#27]
Buenos días. 
Tengo tomcat 7, y a la hora de desplegar los war, algunos dan errores, pero sin darme muchas pistas de que falla.
Entre ellos están: 
SIGEM_PortafirmasNotificacionWS
SIGEM_RegistroPresencialMSSSIWeb
SIGEM_GestionCSVWeb

He probado a desplegar SIGEM_PortafirmasNotificacionWS en tomcat 8 y si que despliega sin errores.

¿Así que mi pregunta es que versión de tomcat es necesaria para que funcione el proyecto completo? ¿O es un problema de configuración del tomcat 7 por lo que me fallan esos proyectos? ¿Falta de librerías quizás?

Gracias!

**Comment by mqelvira** [comment]
Buenos días. 
Nosotros tenemos en algunas máquinas (tramitador, registro, etc.) la versión 6.0.44 y en otras la 8.0.29 (sigem_scheduler, sigem_orve, port@firmas, etc), No veo que tengamos tomcat 7 en ninguna, no te puedo decir si porque fallaba o si porque cuando nos ponemos a actualizar nos vamos a la última que haya y nos saltamos la 7.
En desarrollo tenemos la 6.0.44 y funciona todo.

**Comment by agustinjm** [comment]
Buenos días, tengo una máquina con Tomcat 7.0.16 funcionando sin problema. Yo miraría la versión de java, esta máquina tiene la OpenJDK 1.7.0_141. Comentar que la máquina tarda doble en arrancar que el Tomcat 6, pero es mucho más robusto ante redespliegues. Saludos.

**Comment by joseagudomontero** [comment]
AleDH, si te da errores deben estar en el catalina.out o en el log del servicio correspondiente. Si posteas el error quizás pueda ayudarte, yo he conseguido desplegar en 

apache-tomcat-7.0.82
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)

Sobre un servidor windows,. A la hora de desplegar este ha sido uno de ellos relacionado con el servicio de arranque. No se si es el mismo que el tuyo.

Problema
SEVERE: Servlet.service() for servlet jsp threw exception
javax.el.ELException: The identifier [case] is not a valid Java identifier as required by section 1.19 of the EL specification (Identifier ::= Java language identifier). This check can be disabled by setting the system property org.apache.el.parser.SKIP_IDENTIFIER_CHECK to true

It is due to in tomcat 7 by default SKIP IDENTIFIER CHECK feature is false(which was true in tomcat 6 and below) and I use "case" in regular expression and case is identifier so it throws error.

Solución
Poner en el arranque de Tomcat
-Dorg.apache.el.parser.SKIP_IDENTIFIER_CHECK=true


Mira el TOMCAT_HOME\logs\*

Busca las palabras ERROR y GRAVE con alguna utilidad y a ver que puede estar impidiendo que arranques.

**Comment by AleDH** [comment]
Este es el error que me da para SIGEM_PortafirmasNotificacionWS

`12:19:57,309 ERROR [context.support.XmlWebApplicationContext] Exception thrown from ApplicationListener handling ContextClosedEvent
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'cxf': Singleton bean creation not allowed while the singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:209)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.context.event.AbstractApplicationEventMulticaster.getApplicationListeners(AbstractApplicationEventMulticaster.java:148)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:86)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:301)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:984)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:947)
	at org.apache.cxf.bus.spring.SpringBus.destroyBeans(SpringBus.java:131)
	at org.apache.cxf.bus.CXFBusImpl.shutdown(CXFBusImpl.java:217)
	at org.apache.cxf.bus.CXFBusImpl.shutdown(CXFBusImpl.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:273)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:199)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:486)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:462)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:430)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1018)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:431)
	at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:282)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:204)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4723)
	at org.apache.catalina.core.StandardContext$1.call(StandardContext.java:5226)
	at org.apache.catalina.core.StandardContext$1.call(StandardContext.java:5221)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
12:19:57,310 ERROR [web.context.ContextLoader] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sigem_servicioPortafirmasNotificacionEndpoint': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.apache.ws.commons.schema.XmlSchemaCollection.read(Lorg/w3c/dom/Document;Ljava/lang/String;)Lorg/apache/ws/commons/schema/XmlSchema;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1412)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:563)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:872)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:423)
	at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:282)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:204)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4723)
	at org.apache.catalina.core.StandardContext$1.call(StandardContext.java:5226)
	at org.apache.catalina.core.StandardContext$1.call(StandardContext.java:5221)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.apache.ws.commons.schema.XmlSchemaCollection.read(Lorg/w3c/dom/Document;Ljava/lang/String;)Lorg/apache/ws/commons/schema/XmlSchema;
	at org.apache.cxf.common.xmlschema.SchemaCollection.read(SchemaCollection.java:133)
	at org.apache.cxf.databinding.AbstractDataBinding.addSchemaDocument(AbstractDataBinding.java:190)
	at org.apache.cxf.databinding.AbstractDataBinding.addSchemaDocument(AbstractDataBinding.java:93)
	at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:350)
	at org.apache.cxf.service.factory.AbstractServiceFactoryBean.initializeDataBindings(AbstractServiceFactoryBean.java:86)
	at org.apache.cxf.service.factory.ReflectionServiceFactoryBean.buildServiceFromClass(ReflectionServiceFactoryBean.java:445)
	at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.buildServiceFromClass(JaxWsServiceFactoryBean.java:685)
	at org.apache.cxf.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.java:508)
	at org.apache.cxf.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:242)
	at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:205)
	at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:101)
	at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:159)
	at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:207)
	at org.apache.cxf.jaxws.EndpointImpl.getServer(EndpointImpl.java:438)
	at org.apache.cxf.jaxws.EndpointImpl.doPublish(EndpointImpl.java:325)
	at org.apache.cxf.jaxws.EndpointImpl.publish(EndpointImpl.java:242)
	at org.apache.cxf.jaxws.EndpointImpl.publish(EndpointImpl.java:516)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1536)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1477)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1409)
	... 19 more
oct 01, 2019 12:19:57 PM org.apache.catalina.core.StandardContext startInternal
GRAVE: Error listenerStart
oct 01, 2019 12:19:57 PM org.apache.catalina.core.StandardContext startInternal
GRAVE: Falló en arranque del Contexto [/SIGEM_PortafirmasNotificacionWS] debido a errores previos`

**Comment by AleDH** [comment]
He probado por si acaso a cambiar a java 7 openjdk, pero me siguen dando los mismos fallos.

Error que me da SIGEM_RegistroPresencialMSSSIWeb
`oct 01, 2019 12:19:29 PM com.sun.faces.config.ConfigureListener contextInitialized
INFORMACIÓN: Inicializando Mojarra 2.1.1 (SNAPSHOT 20110404) para el contexto '/SIGEM_RegistroPresencialMSSSIWeb'
oct 01, 2019 12:19:30 PM com.sun.faces.spi.InjectionProviderFactory createInstance
INFORMACIÓN: JSF1048: hay presentes anotaciones PostConstruct/PreDestroy.  Los métodos de beans administrados marcados con estas anotaciones procesarán dichas anotaciones.
oct 01, 2019 12:19:32 PM org.primefaces.webapp.PostConstructApplicationEventListener processEvent
INFORMACIÓN: Running on PrimeFaces 4.0
oct 01, 2019 12:19:32 PM org.apache.catalina.core.StandardContext startInternal
GRAVE: Error listenerStart
oct 01, 2019 12:19:32 PM org.apache.catalina.core.StandardContext startInternal
GRAVE: Falló en arranque del Contexto [/SIGEM_RegistroPresencialMSSSIWeb] debido a errores previos
oct 01, 2019 12:19:32 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads`
