### ISSUE TITLE
En el despliegue de los WAR, no encuentra el fichero menuMacros.vm

### ISSUE THREAD

**Issue by fsolans** [ctt-gob-es/SIGM#8]
Hola,

Desplegado los WAR del proyecto en CentOS 7 y Tomcat 7 sobre PostgreSQL 9, me sale el siguiente error:

org.apache.velocity.exception.VelocityException: Velocimacro : Error using VM library : menuMacros.vm
        at org.apache.velocity.runtime.VelocimacroFactory.initVelocimacro(VelocimacroFactory.java:219)
        at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:274)
        at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:646)
        at org.apache.velocity.app.VelocityEngine.init(VelocityEngine.java:116)
        at net.sf.navigator.displayer.VelocityMenuDisplayer.initialize(VelocityMenuDisplayer.java:71)
        at net.sf.navigator.menu.MenuRepository.addMenuDisplayerMapping(MenuRepository.java:168)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:622)
        at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:216)
        at org.apache.commons.digester.SetNextRule.end(SetNextRule.java:208)
        at org.apache.commons.digester.Rule.end(Rule.java:228)
        at org.apache.commons.digester.Digester.endElement(Digester.java:1067)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.commons.digester.Digester.parse(Digester.java:1591)
        at net.sf.navigator.menu.MenuRepository.load(MenuRepository.java:202)
        at net.sf.navigator.menu.MenuPlugIn.init(MenuPlugIn.java:58)
        at org.apache.struts.action.ActionServlet.initModulePlugIns(ActionServlet.java:839)
        at org.apache.struts.action.ActionServlet.init(ActionServlet.java:332)
        at javax.servlet.GenericServlet.init(GenericServlet.java:160)
        at ieci.tdw.ispac.ispacweb.servlet.ISPACActionServlet.init(ISPACActionServlet.java:28)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1201)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1114)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1021)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4957)
        at org.apache.catalina.core.StandardContext$3.call(StandardContext.java:5284)
        at org.apache.catalina.core.StandardContext$3.call(StandardContext.java:5279)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)
Caused by: org.apache.velocity.exception.ResourceNotFoundException: **Unable to find resource 'menuMacros.vm'**
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
        at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
        at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1514)
        at org.apache.velocity.runtime.VelocimacroFactory.initVelocimacro(VelocimacroFactory.java:202)
        ... 41 more

Lo he buscado en el proyecto y tampoco lo he encontrado. ¿ Alguna pista ?

**Comment by jmbob** [comment]
Se ha incluido el fichero en el proyecto para que no de errores. Ver commit UPNA-001.
